import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { api } from "../utils/api";
import { useState } from "react";

const SubmitBuildPage: NextPage = () => {
  const createBuildMutation = api.builds.createBuild.useMutation();

  const [matchUp, setMatchUp] = useState("zvt");
  const [build, setBuildOrder] = useState("");

  const router = useRouter();

  async function handleSubmitBuildOrder(e: React.FormEvent) {
    e.preventDefault();

    console.log(matchUp);
    console.log(build);

    await createBuildMutation.mutateAsync({
      matchUp,
      build,
    });

    await router.push("/builds");
  }

  return (
    <>
      <Head>
        <title>Submit a Build</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Submit a Build Order</h1>

        <form
          onSubmit={(e) => void handleSubmitBuildOrder(e)}
          className="flex flex-col gap-4"
        >
          <label htmlFor="match-up-select">Match Up</label>
          <select
            onChange={(e) => setMatchUp(e.target.value)}
            value={matchUp}
            name=""
            id="match-up-select"
            className="text-black"
            required
          >
            <option value="zvt">ZvT</option>
            <option value="zvp">ZvP</option>
            <option value="zvz">ZvZ</option>

            <option value="pvt">PvT</option>
            <option value="pvp">PvP</option>
            <option value="pvz">PvZ</option>

            <option value="tvt">TvT</option>
            <option value="tvp">TvP</option>
            <option value="tvz">TvZ</option>
          </select>

          <textarea
            value={build}
            className="p-2 text-black"
            onChange={(e) => setBuildOrder(e.target.value)}
            required
          />

          <button className="bg-white p-2 text-black">submit</button>
        </form>
      </main>
    </>
  );
};

export default SubmitBuildPage;
